# Generated by Django 5.1.7 on 2025-05-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_login_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('studentID', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
