# Generated by Django 5.1.7 on 2025-05-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_login_details',
            name='password',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='student_login_details',
            name='studentID',
            field=models.IntegerField(),
        ),
    ]
