# Generated by Django 5.1.7 on 2025-05-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_alter_student_login_details_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('father', models.CharField(max_length=30)),
                ('mother', models.CharField(max_length=30)),
                ('studentID', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=25)),
            ],
        ),
    ]
