# Generated by Django 5.1.7 on 2025-06-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_studentdetails_delete_studentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegInfoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.IntegerField()),
                ('ProvidedStNumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=120)),
                ('ST_NUMBER', models.CharField(max_length=15)),
                ('cls', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='students/')),
                ('StudentID', models.IntegerField()),
            ],
        ),
    ]
