# Generated by Django 5.1.7 on 2025-06-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0007_studentreginfoadmin_studentreglogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreginfoadmin',
            name='ProvidedStNumber',
            field=models.CharField(max_length=30),
        ),
    ]
