# Generated by Django 5.1.7 on 2025-05-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='secret_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teacher_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=120)),
                ('m_number', models.IntegerField()),
                ('NID', models.IntegerField()),
            ],
        ),
    ]
