# Generated by Django 5.1.7 on 2025-05-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0003_teacherdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.IntegerField()),
                ('Join_date', models.DateTimeField()),
                ('add', models.CharField(max_length=55)),
                ('sub', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherDate',
        ),
    ]
