# Generated by Django 5.1.7 on 2025-06-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0005_newapplystudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdata',
            name='image',
            field=models.ImageField(upload_to='TeachersImage/'),
        ),
    ]
