# Generated by Django 5.1.7 on 2025-06-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0006_alter_teacherdata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.IntegerField()),
                ('Join_date', models.DateTimeField()),
                ('add', models.CharField(max_length=55)),
                ('sub', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='TeachersImage/')),
                ('ST_COODE', models.CharField(max_length=18)),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherData',
        ),
    ]
