# Generated by Django 5.1.7 on 2025-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0007_teacherdatas_delete_teacherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdatas',
            name='NID',
            field=models.IntegerField(null=True),
        ),
    ]
