# Generated by Django 5.1.7 on 2025-06-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0008_teacherdatas_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdatas',
            name='Join_date',
            field=models.DateField(),
        ),
    ]
